language: c
compiler: gcc
dist: xenial
install:
  - make clean && make

before_script:
  - git clone --depth 1 https://github.com/antirez/redis.git
  - cd redis
  - make
  - cd ..
  - sudo pip install redis ramp-packer rmtest

env:
  - REDIS_MODULE_PATH=$TRAVIS_BUILD_DIR/src/rejson.so
  - REDIS_PATH=$TRAVIS_BUILD_DIR/redis/src/redis-server

script:
  - make test
  - make package

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET
    skip_cleanup: true
    acl: public_read
    bucket: redismodules
    upload-dir: rejson
    on:
      branch: master
    local_dir: $TRAVIS_BUILD_DIR/build
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET
    skip_cleanup: true
    acl: public_read
    bucket: rejson.io
    on:
      branch: gh-pages
    local_dir: $TRAVIS_BUILD_DIR/site