language: c
compiler: gcc
dist: trusty

branches:
  only:
    - master

addons:
    packages:
      - cmake
      - cmake-data

before_install:
  - sudo apt-get install cmake
  - git clone --depth 1 https://github.com/antirez/redis.git
  - cd redis
  - make
  - cd ..
  - pip install redis

install:
  - ./bootstrap.sh
  - cmake -DREDIS_SERVER_PATH:FILEPATH=$PWD/redis/src/redis-server --build build
  - cmake --build build --target all --config Release

script:
  - cd build
  - ctest -VV
