language: c
compiler: gcc
dist: trusty
install: make clean && make

before_script:
  - git clone --depth 1 https://github.com/antirez/redis.git
  - cd redis
  - make
  - cd ..
  - pip install redis

env:
  - REDIS_MODULE_PATH=$TRAVIS_BUILD_DIR/src/rejson.so REDIS_PATH=$TRAVIS_BUILD_DIR/redis/src/redis-server

script: make test