language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8.3

branches:
  only:
    - master

before_install:
  - git clone --depth 1 https://github.com/antirez/redis.git
  - cd redis
  - make
  - cd ..
  - pip install redis rmtest

install:
  - make all

script:
  - make test