language: c

branches:
  only:
    - master

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data

before_install:
  - sudo apt-get install cmake
  - git clone https://github.com/antirez/redis.git
  - cd redis
  - make
  - cd ..
  - sudo apt-get install python python-pip
  - sudo -H pip install redis

install:
  - ./bootstrap.sh
  - cmake -DREDIS_SERVER_PATH:FILEPATH=./redis/src/redis-server --build build
  - cmake --build build --target all --config Release

script:
  - cd build
  - ctest -V -j 1
