language: c
compiler: gcc
dist: trusty

env:
  global:
    - MODULE_NAME=rejson
    - REDIS_MODULE_PATH=$TRAVIS_BUILD_DIR/src/rejson.so
    - REDIS_PATH=$TRAVIS_BUILD_DIR/redis/src/redis-server

install:
  - make clean && make

before_script:
  - git clone --depth 1 https://github.com/antirez/redis.git
  - cd redis
  - make
  - cd ..
  - pip install --user redis rmtest ramp-packer==1.2.3

script:
  - make test

before_deploy:
  - make package

deploy:
  # Module latest artifact
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET
    skip_cleanup: true
    acl: public_read
    bucket: redismodules
    upload-dir: $MODULE_NAME
    on:
      branch: master
    local_dir: $TRAVIS_BUILD_DIR/build
