language: c
compiler: gcc
before_install:
  - git clone https://github.com/antirez/redis.git
  - cd redis
  - make
  - cd ..
install:
  - ./bootstrap.sh
  - cmake -DREDIS_SERVER_PATH:FILEPATH=./redis/src/redis-server --build build
  - cmake --build build --target all --config Release
script:
  - cd build
  - ctest -V