[package]
name = "redisjson"
version = "0.1.0"
authors = ["Gavrie Philipson <gavrie@redislabs.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde_json = "1.0"
libc = "0.2"
jsonpath = "0.1.1"
redismodule = { path = "redismodule-rs", version = "0.1.0" }
